#사이킷런(scikit-learn)
파이썬 머신러닝 라이브러리 

## Framework


* Estimator : 지도학습의 모든 알고리즘을 구현한 클래스 
* fit : ML 모델 학습
* predict : 학습된 모델의 예측

## Model Selection Module

 ### Train_Test_Split

In [2]:
from sklearn.datasets import load_iris

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split

In [3]:
iris_data = load_iris() #sklearn 내장 데이터 'iris' 로드
dt_clf = DecisionTreeClassifier()

In [5]:
#train/test data 분할
#random_state = : 호출 때마다 동일한 데이터 셋을 생성하기 위해 주어지는 난수 값 (미지정시 수행할 때마다 다른 데이터 셋을 생산)

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size = 0.3, random_state = 121)

In [6]:
dt_clf.fit(X_train, y_train) #모델 적합
pred = dt_clf.predict(X_test) #적합한 모델로 예측

In [7]:
print("예측 정확도: {0:.4f}".format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556


교차 검증(Cross Validation)

### K-fold 

In [15]:
import numpy as np

In [10]:
from sklearn.model_selection import KFold

In [11]:
iris = load_iris()
features = iris.data
label = iris.target

In [12]:
kfold = KFold(n_splits = 5) # K = 5 설정
cv_accuracy = [] #각 fold set 별 정확도를 담을 리스트 객체 생성

In [14]:
n_iter = 0 #반복 횟수

#KFold 객체의 split() 호출 시, fold 별 train/test data의 raw index를 array로 반환
for train_index, test_index in kfold.split(features):

  #train/test data set 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]

  #fit & predict
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1 

  #각 iteration 별로 accuracy 측정
  accuracy = np.round(accuracy_score(y_test, pred), 4)

  train_size = X_train.shape[0]
  test_size = X_test.shape[0]

  print("\n#{0} 교차 검증 정확도 : {1}, 학습 데이터의 크기 : {2}, 검증 데이터의 크기 : {3}".format(n_iter, accuracy, train_size, test_size))
  print("#{0} 검증 세트 인덱스 : {1}".format(n_iter, test_index))
  cv_accuracy.append(accuracy)

print("\n## 평균 검증 정확도 : ", np.mean(cv_accuracy)) #개별 iteration별 accuracy를 합하여 평균 정확도 계산


#1 교차 검증 정확도 : 1.0, 학습 데이터의 크기 : 120, 검증 데이터의 크기 : 30
#1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 : 1.0, 학습 데이터의 크기 : 120, 검증 데이터의 크기 : 30
#2 검증 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 : 0.8667, 학습 데이터의 크기 : 120, 검증 데이터의 크기 : 30
#3 검증 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 : 0.9333, 학습 데이터의 크기 : 120, 검증 데이터의 크기 : 30
#4 검증 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 : 0.7333, 학습 데이터의 크기 : 120, 검증 데이터의 크기 : 30
#5 검증 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도 :  0.9066599999999999


### Stratified K-fold


> 원본 데이터의 레이블 분포를 먼저 고려한 뒤, 이 분포와 동일하게 Train/Test Data Set을 분배



In [19]:
import pandas as pd

In [20]:
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df["label"] = iris.target
iris_df["label"].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [16]:
from sklearn.model_selection import StratifiedKFold

In [26]:
dt_clf = DecisionTreeClassifier(random_state = 156)

skfold = StratifiedKFold(n_splits = 3)
n_iter = 0 #반복 횟수
cv_accuracy = []

#KFold 객체의 split() 호출 시, fold 별 train/test data의 raw index를 array로 반환
for train_index, test_index in skfold.split(features, label):

  #train/test data set 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]

  #fit & predict
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1 

  #각 iteration 별로 accuracy 측정
  accuracy = np.round(accuracy_score(y_test, pred), 4)

  train_size = X_train.shape[0]
  test_size = X_test.shape[0]

  print("\n#{0} 교차 검증 정확도 : {1}, 학습 데이터의 크기 : {2}, 검증 데이터의 크기 : {3}".format(n_iter, accuracy, train_size, test_size))
  print("#{0} 검증 세트 인덱스 : {1}".format(n_iter, test_index))
  cv_accuracy.append(accuracy)

print("\n## 평균 검증 정확도 : ", np.mean(cv_accuracy)) #개별 iteration별 accuracy를 합하여 평균 정확도 계산


#1 교차 검증 정확도 : 0.98, 학습 데이터의 크기 : 100, 검증 데이터의 크기 : 50
#1 검증 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.94, 학습 데이터의 크기 : 100, 검증 데이터의 크기 : 50
#2 검증 세트 인덱스 : [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.98, 학습 데이터의 크기 : 100, 검증 데이터의 크기 : 50
#3 검증 세트 인덱스 : [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도 :  0.9666666666666667


cross_val_score()


> API 내부에서 Estimator의 학습, 예측, 평가를 진행



In [27]:
from sklearn.model_selection import cross_val_score, cross_validate

In [30]:
data = iris_data.data
label = iris_data.target

In [31]:
scores = cross_val_score(dt_clf, data, label, scoring = "accuracy", cv = 3)
print("교차 검증별 정확도: ", np.round(scores, 4))
print("평균 검증 정확도: ", np.round(np.mean(scores), 4))

교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


### GridSearchCV


> 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에 진행

## Data Preprocessing

### Data Encoding

레이블 인코딩(Label Encoding) 
> 카테고리형 feature를 코드형 숫자 값으로 변환 

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
items = ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "믹서", "믹서"]

encoder = LabelEncoder() #LabelEncoder 객체 생성
encoder.fit(items)
labels = encoder.transform(items)

print("인코딩 변환 값: ", labels)
print("인코딩 클래스: ", encoder.classes_)
print("디코딩 원본값: ", encoder.inverse_transform([4, 5, 1, 2, 2, 3, 0]))

인코딩 변환 값:  [0 1 4 5 3 2 2]
인코딩 클래스:  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값:  ['전자레인지' '컴퓨터' '냉장고' '믹서' '믹서' '선풍기' 'TV']


원-핫 인코딩(One Hot Encoding)
> feature value의 유형에 따라 새로운 feature를 추가해 고유값에 해당하는 컬럼에만 1을 표시, 나머지는 0

In [34]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
items = ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

#숫자 값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder() #LabelEncoder 객체 생성
encoder.fit(items)
labels = encoder.transform(items)

#2차원 데이터로 변환
labels = labels.reshape(-1, 1)

#One-Hot Encoding
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print("원-핫 인코딩 데이터")
print(oh_labels.toarray())
print()

print("원-핫 인코딩 데이터 차원: ", oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]

원-핫 인코딩 데이터 차원:  (8, 6)


In [37]:
#Pandas get_dummies(): 원-핫 인코딩 지원 API'
#숫자형 값으로 변환하지 않아도 됨
import pandas as pd

df = pd.DataFrame({
    "item" : ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]
})

pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### Feature Scailing

StandardScaler(표준화)

> 가우시안 정규분포를 따르도록 데이터 변환 



In [39]:
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

In [40]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [41]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
scaler = StandardScaler() #객체 생성
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) #Numpy ndarray로 반환됨

In [44]:
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names) #데이터프레임으로 변환 

In [47]:
iris_df_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [48]:
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

MinMaxScaler
 > 데이터 값을 0과 1사이의 범위 값으로 변환

In [49]:
from sklearn.preprocessing import MinMaxScaler

In [50]:
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [51]:
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

In [52]:
print("features의 최댓값")
print(iris_df_scaled.max())
print()

print("features의 최솟값")
print(iris_df_scaled.min())

features의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

features의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64


* 전체 데이터의 스케일링 변환 후 학습/테스트 데이터로 분리
* 위가 여의치 않다면, 테스트 데이터 변환시에는 학습 데이터로 이미 fit()된 Scaler 객체를 이용해 transform으로 변환