In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [3]:
import numpy as np

In [4]:
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
            ], dtype = "float32")

y = np.array([
            [0],
            [0],
            [0],
            [1]
], dtype = "float32")

In [5]:
model = Sequential() #입력값을 읽어 예측할 객체
model.add(Dense(1, input_dim = 2, activation = "sigmoid")) #Dense 모델을 예측할 수 있도록 model에 추가
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [6]:
#Gradient Decent를 이용해 W, b를 찾는 방법 설정
model.compile(loss = "binary_crossentropy", optimizer = Adam(lr = 0.1), metrics = ["acc"])

In [7]:
model.fit(X, y, epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6938 - acc: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6687 - acc: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6448 - acc: 1.0000
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6219 - acc: 1.0000
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5998 - acc: 1.0000
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5787 - acc: 1.0000
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5585 - acc: 1.0000
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5390 - acc: 1.0000
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5204 - acc: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5026 - acc: 1.0000
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4857 

In [12]:
pred = model.predict(X) #예측값
predict01 = np.where(pred > 0.5, 1, 0)
predict01

array([[0],
       [0],
       [0],
       [1]])

In [13]:
predict02 = predict01.flatten() #1차원 배열로 변환
predict02

array([0, 0, 0, 1])

In [15]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [16]:
predict03 = (predict02 == y.flatten())
predict03

array([ True,  True,  True,  True])

In [17]:
acc = np.sum(predict03) / 4 #정확도
acc

1.0