인공신경망을 이용한 AND 연산

Sigmoid Function
* 선형 회귀의 결과를 0 또는 1로 리턴하는 함수
* 선형 회귀 식 ax + b 의 결과를 0 / 1 로 리턴하는 Sigmoid Function 
  * y = 1 / (1 + e^((-)(Wx + b))
  * 구해야 할 것: W, b




In [1]:
#자연상수 e
from math import e
e

2.718281828459045

In [2]:
import numpy as np

In [3]:
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
            ], dtype = "float32")

In [4]:
y = np.array([
            [0],
            [0],
            [0],
            [1]
], dtype = "float32")

In [5]:
w = np.array([
              [1],
              [2]
], dtype = "float32")
b = np.array([3], dtype = "float32")

In [7]:
#Sigmoid Function 선언
def sigmoid(h):
  return 1 / (1 + e ** -h)

In [9]:
hypothesis = sigmoid(np.dot(X, w) + b) #예측값 계산 & 0 ~ 1 사이의 값으로 변환
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [10]:
hypothesis - y #예측값 - 실제값

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [11]:
#X.T[0] 를 2차원 배열로 변환
X_col_2d1 = X.T[0].reshape(1,-1)
X_col_2d1

array([[0., 0., 1., 1.]], dtype=float32)

In [12]:
#w의 수정값: w1
w1_gred = 1 / 4 * np.sum(np.dot(X_col_2d1, (hypothesis - y)))
print("w1_gred: ", w1_gred)

w1_gred:  0.24488529562950134


In [13]:
#같은 방법으로 X.T[1]을 2차원 배열로 변환, w의 수정값 w2 계산\
X_col_2d2 = X.T[1].reshape(1,-1)
w2_gred = 1 / 4 * np.sum(np.dot(X_col_2d2, (hypothesis - y)))
print("w2_gred: ", w2_gred)

w2_gred:  0.24770864844322205


In [14]:
#b의 수정값
b_gred = 1 / 4 * np.sum(hypothesis - y)
print("b_gred: ", b_gred)

b_gred:  0.731355607509613


In [15]:
learning_rate = 0.1

#1000번 반복, 오차 제곱합이 0으로 수렴되는 w, b 찾기
for i in range(1000):
  for j in range(2):
    hypothesis = sigmoid(np.dot(X, w) + b)
    print("hypothesis: ", hypothesis)

    cost = -1/4 * (y * np.log(hypothesis) + 
              (1 - y) * np.log(1 - hypothesis))
    print("cost: ", cost)

    #X의 행렬 전치, j번째 칸을 리턴해 2차원 배열로 생성
    X_col_2d = X.T[j].reshape(1, -1)

    #w의 기울기 계산
    w_gred = 1 / 4 * np.sum(np.dot(X_col_2d, (hypothesis - y)))
    print("w_{}gred: {}".format(i, w_gred))
    w[j] = w[j] - learning_rate * w_gred #업데이트
    print("w{}: {}".format(j, w))

    #b의 기울기 계산
    b_gred = 1 / 4 * np.sum(hypothesis - y)
    print("b{}_gred: {}".format(1, b_gred))
    b = b - learning_rate * b_gred
    print("b: {}".format(b))

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [0.03365902]
 [0.05762599]]
w_807gred: -0.018711190670728683
w1: [[3.241976 ]
 [3.2890003]]
b1_gred: 0.014180734753608704
b: [-5.1805005]
hypothesis:  [[0.00559373]
 [0.13107352]
 [0.12581006]
 [0.79420745]]
cost:  [[0.00140236]
 [0.03512419]
 [0.03361439]
 [0.05760264]]
w_808gred: -0.01999562233686447
w0: [[3.2439756]
 [3.2890003]]
b1_gred: 0.014171190559864044
b: [-5.1819177]
hypothesis:  [[0.00558585]
 [0.1309122 ]
 [0.12587413]
 [0.79430264]]
cost:  [[0.00140038]
 [0.03507778]
 [0.03363273]
 [0.05757268]]
w_808gred: -0.018696289509534836
w1: [[3.2439756]
 [3.29087  ]]
b1_gred: 0.014168709516525269
b: [-5.1833344]
hypothesis:  [[0.00557798]
 [0.13096374]
 [0.12571833]
 [0.7943765 ]]
cost:  [[0.0013984 ]
 [0.03509261]
 [0.03358818]
 [0.05754944]]
w_809gred: -0.01997629553079605
w0: [[3.2459733]
 [3.29087  ]]
b1_gred: 0.014159135520458221
b: [-5.18475]
hypothesis:  [[0.00557014]
 [0.1308027 ]
 [0.12578231]
 [0.7944716 ]]
cost:  [[0.00139642]
 [0.03

In [16]:
predict = sigmoid(np.dot(X, w) + b)
predict

array([[0.0033861 ],
       [0.11287721],
       [0.11004741],
       [0.82240736]], dtype=float32)

In [17]:
predict01 = np.where(predict >= 0.5, 1, 0)
predict01

array([[0],
       [0],
       [0],
       [1]])

In [19]:
predict02 = (predict01 == y)
predict02

array([[ True],
       [ True],
       [ True],
       [ True]])

In [21]:
acc = np.sum(predict02) / 4 #정확도 계산
acc

1.0

In [22]:
#0, 1의 AND 연산 실행
arr = np.array([[0, 1]], dtype = "float32")
predict = sigmoid(np.dot(arr, w) + b)
predict01 = np.where(predict >= 0.5, 1, 0)
predict01

array([[0]])

In [23]:
#1, 1의 AND 연산 실행
arr = np.array([[1, 1]], dtype = "float32")
predict = sigmoid(np.dot(arr, w) + b)
predict01 = np.where(predict >= 0.5, 1, 0)
predict01

array([[1]])