In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import tensorflow as tf

In [3]:
import numpy as np

In [4]:
tf.enable_eager_execution()

In [5]:
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
            ], dtype = "float32")

y = np.array([
            [0],
            [0],
            [0],
            [1]
], dtype = "float32")

In [6]:
w = tf.Variable([[1], [2]], dtype = "float32")
b = tf.Variable([3], dtype = "float32")

In [7]:
tf.sigmoid(tf.matmul(X, w) + b)

<tf.Tensor: id=20, shape=(4, 1), dtype=float32, numpy=
array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)>

In [8]:
#w, b 값을 자동으로 수정하는 Optimizer 객체
optimizer = tf.train.AdamOptimizer(0.01)

In [ ]:
for step in range(5000):
  with tf.GradientTape() as tape:
    hypothesis = tf.sigmoid(tf.matmul(X, w) + b)
    cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1 - y) * tf.log(1 - hypothesis))
    grads = tape.gradient(cost, [w, b])

  optimizer.apply_gradients(grads_and_vars = zip(grads, [w, b]))

  if step % 100 == 0:
    print("=" * 50)
    print("step: {}, cost: {}, w: {}, b: {}".format(step, cost.numpy(), w.numpy(), b.numpy()))

In [10]:
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[7.0477467],
       [7.0392036]], dtype=float32)>

In [11]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-10.636643], dtype=float32)>

In [13]:
predict = tf.sigmoid(tf.matmul(X, w) + b)
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)
predict01

<tf.Tensor: id=315097, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)>

In [16]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype = tf.float32))
accuracy.numpy()

1.0

In [17]:
#0, 1의 AND 연산 실행
arr = np.array([[0, 1]], dtype = "float32")
predict = tf.sigmoid(tf.matmul(arr, w) + b)
predict = tf.cast(predict > 0.5, dtype = tf.float32)
predict.numpy()

array([[0.]], dtype=float32)

In [18]:
#1, 1의 AND 연산 실행
arr = np.array([[1, 1]], dtype = "float32")
predict = tf.sigmoid(tf.matmul(arr, w) + b)
predict = tf.cast(predict > 0.5, dtype = tf.float32)
predict.numpy()

array([[1.]], dtype=float32)