#Tensorflow 1.x

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [ ]:
import numpy as np

In [ ]:
import tensorflow as tf
tf.enable_eager_execution()

In [ ]:
data = datasets.load_breast_cancer() #데이터 로드

In [ ]:
X = data.data #독립변수
X = np.array(X, dtype = "float32") #데이터 타입 변환 

In [ ]:
y = data.target #종속변수(0: 악성, 1: 양성)
y = np.array(y, dtype = "float32")

In [ ]:
#.reshape(): 1차원 배열을 2차원 배열로 변환 
##.reshape(1, -1): 행 형태의 2차원 배열로 변환
##.reshape(-1, 1): 열 형태의 2차원 배열로 변환
y = y.reshape(-1, 1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) #학습/검증 데이터 분할

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
scaler.fit(X_train) #학습 데이터의 평균, 표준편차 계산

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
X_train = scaler.transform(X_train) #학습 데이터 표준화

In [ ]:
#활성함수 선언
def sigmoid(h):
  return 1 / (1 + np.exp(-h))

In [ ]:
initializer = tf.contrib.layers.xavier_initializer() #w, b를 초기화 시키는 객체 생성

In [ ]:
w = tf.Variable(initializer([30, 1])) #w 생성(행: 30, 열: 1)
b = tf.Variable(initializer([1])) #b 생성(행: 1, 열: 1)

In [ ]:
tf.matmul(X_train, w) + b #선형 회귀 계산

<tf.Tensor: id=44, shape=(455, 1), dtype=float32, numpy=
array([[ 0.21723765],
       [-0.3796893 ],
       [-2.1516414 ],
       [-2.0113454 ],
       [ 0.06772143],
       [ 0.4705125 ],
       [-0.04325366],
       [ 2.2866716 ],
       [-1.250954  ],
       [ 0.1540404 ],
       [-1.7259668 ],
       [-0.979723  ],
       [-0.6178839 ],
       [-0.91488457],
       [-0.9058411 ],
       [ 0.03649157],
       [-1.6046948 ],
       [-0.5531515 ],
       [-3.7879753 ],
       [ 0.81234944],
       [-1.2311265 ],
       [-0.42827147],
       [ 0.6268941 ],
       [ 0.4112442 ],
       [-0.34346384],
       [ 1.0491999 ],
       [ 0.59175634],
       [ 0.2403068 ],
       [ 0.9939239 ],
       [-2.5608284 ],
       [-2.0598092 ],
       [ 0.76542354],
       [ 0.97863793],
       [ 2.0257487 ],
       [-1.0917244 ],
       [ 0.32196814],
       [ 0.83129144],
       [ 1.1865268 ],
       [ 2.2322829 ],
       [-2.6478906 ],
       [ 0.280218  ],
       [ 1.7328808 ],
       [ 0.158984  

In [ ]:
hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b) #X_train 선형 회귀 계산

In [ ]:
optimizer = tf.train.AdamOptimizer(0.001) #w, b를 자동으로 수정하는 Optimizer 객체 생성

In [ ]:
#반복해서 최적의 w, b를 찾음
for step in range(100):
  with tf.GradientTape() as tape:
    #로지스틱 회귀식을 변수 hypothesis에 대입
    hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b)
    #로지스틱 회귀식의 오차 계산식을 변수 cost에 대입
    #Tensorflow에서 자동으로 오차를 가장 적게하는 w, b를 찾음
    cost = -tf.reduce_mean(y_train * tf.log(hypothesis) + (1 - y_train) * tf.log(1 - hypothesis))

    #cost, w, b를 이용해 w의 기울기, b의 기울기를 계산해 grads에 대입
    grads = tape.gradient(cost, [w, b])
  
  #w, b 업데이트
  optimizer.apply_gradients(grads_and_vars = zip(grads, [w, b]))

  if step % 10 == 0:
    print("=" * 50)
    print("step: {}, cost: {}, w: {}, b: {}".format(step, cost.numpy(), w.numpy(), b.numpy()))
    print("=" * 50)

step: 0, cost: 0.6666116118431091, w: [[-0.00076325]
 [ 0.35696107]
 [-0.2524698 ]
 [-0.09100427]
 [-0.11748872]
 [-0.12580232]
 [ 0.09872286]
 [ 0.10195182]
 [-0.10752384]
 [-0.27787805]
 [-0.00118942]
 [ 0.35349226]
 [-0.43328717]
 [-0.11534153]
 [ 0.382909  ]
 [ 0.3264004 ]
 [-0.03763248]
 [-0.05382867]
 [ 0.38454616]
 [-0.36433464]
 [ 0.08076178]
 [ 0.10469846]
 [-0.18052994]
 [ 0.04887014]
 [-0.23353149]
 [ 0.1771522 ]
 [ 0.27352566]
 [-0.38245288]
 [-0.039838  ]
 [-0.40582713]], b: [-0.47495693]
step: 10, cost: 0.6186762452125549, w: [[-0.01072652]
 [ 0.34698737]
 [-0.26243156]
 [-0.10096744]
 [-0.12729222]
 [-0.1357271 ]
 [ 0.08877486]
 [ 0.09199946]
 [-0.11744715]
 [-0.26784202]
 [-0.01115041]
 [ 0.34352484]
 [-0.44324556]
 [-0.12530296]
 [ 0.37303546]
 [ 0.3164885 ]
 [-0.04755311]
 [-0.06376661]
 [ 0.37460822]
 [-0.3719642 ]
 [ 0.07079753]
 [ 0.09472442]
 [-0.19049248]
 [ 0.03890591]
 [-0.24343422]
 [ 0.16721596]
 [ 0.26358008]
 [-0.39240456]
 [-0.04978493]
 [-0.4155769 ]], b:

In [ ]:
#Gradient Decent를 통해 계산이 완료된 w
w

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[-0.08701018],
       [ 0.2674021 ],
       [-0.33836818],
       [-0.17751339],
       [-0.11876182],
       [-0.19965525],
       [ 0.01606324],
       [ 0.01833507],
       [-0.18098216],
       [-0.17771289],
       [-0.0877137 ],
       [ 0.2657225 ],
       [-0.518994  ],
       [-0.20212509],
       [ 0.3212611 ],
       [ 0.25871006],
       [-0.10866828],
       [-0.13057393],
       [ 0.30480433],
       [-0.2632019 ],
       [-0.00601302],
       [ 0.01502723],
       [-0.266865  ],
       [-0.03814371],
       [-0.30169168],
       [ 0.09875631],
       [ 0.19202122],
       [-0.46547064],
       [-0.12229957],
       [-0.38959277]], dtype=float32)>

In [ ]:
#Gradient Decent를 통해 계산이 완료된 b
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.38215223], dtype=float32)>

In [ ]:
X_test = scaler.transform(X_test) #X_train의 평균, 표준편차를 이용해 X_test의 범위를 변경
X_test

array([[-1.0321757 ,  0.03436407, -1.0098044 , ..., -1.2799324 ,
        -0.12322859, -0.46103364],
       [-0.7707439 , -0.42516443, -0.7579875 , ..., -0.7902572 ,
        -0.507186  , -0.1657577 ],
       [-0.42309546,  1.0903504 , -0.39416254, ...,  0.8564842 ,
         0.7605084 ,  1.0359728 ],
       ...,
       [-1.195153  , -0.25110075, -1.1230215 , ..., -0.25328293,
        -0.4595876 ,  1.7470237 ],
       [-0.41197073, -0.3416137 , -0.4630596 , ..., -1.2173262 ,
        -1.1719718 , -1.2898694 ],
       [ 0.50582105,  0.95109934,  0.4120542 , ..., -0.24333337,
         0.07033721,  0.02747442]], dtype=float32)

In [ ]:
predict = tf.sigmoid(tf.matmul(X_test, w) + b) #예측값

In [ ]:
#tf.cast(조건): 조건을 만족하는 데이터 또는 True를 1로 변환 
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)

In [ ]:
#tf.equal(A, B): A = B 이면 True 리턴
ac01 = tf.equal(predict01, y_test)

In [ ]:
#tf.cast(): True는 1로, False는 0으로 변환
ac02 = tf.cast(ac01, dtype = "float32")

In [ ]:
#tf.reduce_mean(): 변환한 0과 1의 합을 구한 후, 데이터의 개수로 나눔
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=6459, shape=(), dtype=float32, numpy=0.8333333>

In [ ]:
#정확도
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y_test), dtype = tf.float32))
print("accuracy: ", accuracy.numpy())

accuracy:  0.8333333
