In [1]:
import numpy as np

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [4]:
data = datasets.load_breast_cancer()

In [5]:
X = data.data
y = data.target

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

In [8]:
model = Sequential()

model.add(Dense(30, input_dim = 30, activation = "sigmoid"))
model.add(Dense(10, activation = "sigmoid"))
model.add(Dense(1, activation = "sigmoid"))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 30)                930       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                310       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 1,251
Trainable params: 1,251
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(loss = "binary_crossentropy", optimizer = Adam(lr = 0.0001), metrics = ["acc"])

In [10]:
model.fit(X_train, y_train, epochs = 1000)

Epoch 1/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6910 - acc: 0.6264
Epoch 2/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6850 - acc: 0.6264
Epoch 3/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6792 - acc: 0.6264
Epoch 4/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6732 - acc: 0.6264
Epoch 5/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.6676 - acc: 0.6264
Epoch 6/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6618 - acc: 0.6264
Epoch 7/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6562 - acc: 0.6264
Epoch 8/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6506 - acc: 0.6264
Epoch 9/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6451 - acc: 0.6264
Epoch 10/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.6396 - acc: 0.6264
Epoch 11/1000
15/15 [============================

In [11]:
X_test = scaler.transform(X_test)

In [12]:
pred = model.predict(X_test)
predict = (np.where(pred > 0.5, 1, 0).flatten()  == y_test)
predict

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False])

In [13]:
np.where(pred > 0.5, 1, 0).flatten()

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

In [14]:
y_test

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0])

In [15]:
acc = np.sum(predict) / len(predict)

In [16]:
acc

0.9736842105263158