XOR 연산 관련은 강의자료 참고

In [2]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [3]:
import tensorflow as tf
from tensorflow.nn import relu
tf.enable_eager_execution()

In [4]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [5]:
import numpy as np

In [6]:
data = datasets.load_breast_cancer()

In [7]:
X = np.array(data.data, dtype = "float32")
y = np.array(data.target, dtype = "float32")
y = y.reshape(-1, 1)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

In [10]:
initializer = tf.contrib.layers.xavier_initializer()

w0 = tf.Variable(initializer([30, 30]))
b0 = tf.Variable(initializer([30]))

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [11]:
w1 = tf.Variable(initializer([30, 10]))
b1 = tf.Variable(initializer([10]))

In [12]:
w2 = tf.Variable(initializer([10, 1]))
b2 = tf.Variable(initializer([1]))

In [13]:
hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
hypothesis2 = tf.sigmoid(tf.matmul(hypothesis1, w2) + b2)

In [14]:
hypothesis2

<tf.Tensor: id=94, shape=(455, 1), dtype=float32, numpy=
array([[0.18295082],
       [0.19630122],
       [0.1682325 ],
       [0.18517095],
       [0.20016101],
       [0.18492848],
       [0.17573711],
       [0.16424486],
       [0.18892482],
       [0.18846643],
       [0.1687178 ],
       [0.19186085],
       [0.15914047],
       [0.17843169],
       [0.18074512],
       [0.17986697],
       [0.18493575],
       [0.18590969],
       [0.18921095],
       [0.17752647],
       [0.18117511],
       [0.1999135 ],
       [0.17153132],
       [0.1814909 ],
       [0.17963174],
       [0.19458777],
       [0.18650717],
       [0.19198433],
       [0.19023174],
       [0.18569526],
       [0.18660644],
       [0.17714486],
       [0.19600058],
       [0.1727536 ],
       [0.18157354],
       [0.18841597],
       [0.18785018],
       [0.1755414 ],
       [0.18769583],
       [0.20456696],
       [0.19021517],
       [0.207088  ],
       [0.2027742 ],
       [0.181714  ],
       [0.18224093]

In [15]:
optimizer = tf.train.AdamOptimizer(0.01)

In [16]:
for step in range(1001):
  with tf.GradientTape() as tape:
    hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
    hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
    hypothesis2 = tf.sigmoid(tf.matmul(hypothesis1, w2) + b2)

    cost = -tf.reduce_mean(y_train * tf.log(hypothesis2) + (1 - y_train) * tf.log(1- hypothesis2))
    grads = tape.gradient(cost, [w0, w1, w2, b0, b1, b2])

    optimizer.apply_gradients(grads_and_vars = zip(grads, [w0, w1, w2, b0, b1, b2]))

In [17]:
w0

<tf.Variable 'Variable:0' shape=(30, 30) dtype=float32, numpy=
array([[-3.82874489e-01,  3.18327069e-01, -2.21822932e-01,
        -1.56161442e-01,  3.05480301e-01, -9.31399539e-02,
        -2.41000876e-01, -1.87519655e-01, -4.77021605e-01,
        -2.03236490e-01, -6.95631206e-02, -1.05551846e-01,
         6.69844031e-01, -3.46435040e-01,  2.52914578e-02,
         2.78782129e-01,  2.15085506e-01,  8.09024125e-02,
        -2.03266174e-01, -4.20133509e-02, -3.76085222e-01,
        -1.60704792e-01,  8.94024521e-02,  2.30711669e-01,
        -2.72625089e-01, -3.84427667e-01, -1.41166344e-01,
         3.05093378e-01, -6.80226609e-02, -8.65084752e-02],
       [-6.59207821e-01,  2.58389294e-01, -8.49627078e-01,
         4.23871279e-02, -1.07911348e-01, -4.01753522e-02,
         6.28497899e-01,  1.96837522e-02,  4.73896563e-01,
        -4.54644021e-03, -5.51271558e-01,  1.43954682e+00,
         1.96436495e-01,  1.71771869e-01, -9.89720821e-02,
         2.39814103e-01,  2.95012861e-01, -2.233706

In [18]:
b0

<tf.Variable 'Variable:0' shape=(30,) dtype=float32, numpy=
array([ 0.19521669,  0.2935289 ,  0.537962  ,  0.20866968, -0.18555315,
        0.30579838, -0.29795283, -0.12466186, -0.00281256, -0.30076587,
       -0.01587312,  0.45806906,  0.32748336,  0.48599127, -0.5214563 ,
       -0.09414402, -0.23737505, -0.2706813 ,  0.3407439 ,  0.24306113,
        0.09082957,  0.7745816 , -0.82111734, -0.1562034 ,  0.43259317,
        0.2828451 , -0.6586019 , -0.853162  ,  0.47240424,  1.0195041 ],
      dtype=float32)>

In [19]:
w1

<tf.Variable 'Variable:0' shape=(30, 10) dtype=float32, numpy=
array([[-0.58856213,  0.5109166 ,  0.41638473,  0.41525504, -0.27778238,
        -0.516249  , -0.552612  ,  0.49317464, -0.49315244,  0.3837541 ],
       [-0.56000584,  0.86647475,  1.1375661 ,  0.7884279 , -0.7771822 ,
        -0.5787217 , -0.33259606,  1.369241  , -0.4267    ,  0.6557114 ],
       [ 0.78378433, -1.4088987 , -1.5023211 , -1.4585068 ,  1.0892789 ,
         0.94999945,  0.58368933, -3.2203276 ,  1.0914605 , -0.66190076],
       [-0.29523277,  1.0099423 ,  0.37668043,  0.36304483, -0.70535624,
        -0.11473659, -0.48989487,  0.7189013 , -0.5031132 ,  0.76771444],
       [ 0.8039218 , -0.6078351 , -0.7891391 , -0.797581  ,  0.62201715,
         0.7900049 ,  0.17997742, -0.86613214,  0.5572111 , -0.72016364],
       [-0.14173338,  0.8229381 ,  0.6039664 ,  0.56167436, -0.4519084 ,
        -0.22513515, -0.4852627 ,  0.45584905, -0.3474662 ,  0.42841965],
       [-0.23642135,  0.4892927 ,  0.08802605,  0.36132

In [20]:
b1

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([-0.43069082, -0.13413097,  0.3136107 ,  0.29105946, -0.29389346,
        0.42565274,  0.5070733 , -0.5126729 ,  0.54155606,  0.30907053],
      dtype=float32)>

In [21]:
w2

<tf.Variable 'Variable:0' shape=(10, 1) dtype=float32, numpy=
array([[-1.3564259],
       [ 1.7711729],
       [ 1.5344584],
       [ 1.1993352],
       [-1.5034565],
       [-1.3328224],
       [-1.61893  ],
       [ 1.6550289],
       [-1.3118936],
       [ 1.7580239]], dtype=float32)>

In [22]:
b2

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.26714954], dtype=float32)>

In [23]:
X_test = scaler.transform(X_test)

In [24]:
hypothesis0 = tf.sigmoid(tf.matmul(X_test, w0) + b0)
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
predict = tf.sigmoid(tf.matmul(hypothesis1, w2) + b2)

In [25]:
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)

In [26]:
ac01 = tf.equal(predict01, y_test)
ac02 = tf.cast(ac01, dtype = "float32")
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=103356, shape=(), dtype=float32, numpy=0.99122804>

In [27]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y_test), dtype = "float32"))
accuracy.numpy()

0.99122804