Overcoming Overfitting
* 더 많은 데이터 활용한다
* Feature 개수를 줄인다 > ! Feature Selection !
* 적절한 Parameters 를 설정한다 > 추후 알고리즘 배울 예정

# 복습

5.3 PCA.ipynb 파일 참고 (분산/공분산 계산)

In [ ]:
import pandas as pd
import numpy as np

## 행렬 연산

In [ ]:
A = np.array([
      [1,2,3],
      [4,5,6]    
])

In [ ]:
B = np.array(
    [
     [100, 500],
     [200, 600],
     [300, 700]
    ]
)

In [ ]:
np.dot(A,B) #행렬 연산 방법1

array([[1400, 3800],
       [3200, 9200]])

In [ ]:
np.matmul(A, B) #행렬 연산 방법2

array([[1400, 3800],
       [3200, 9200]])

## 분산/공분산

In [ ]:
score = np.array([
       [1, 4, 2, 9, 9], #영어 등수
       [3, 2, 7, 3, 10]  #국어 등수   
])

In [ ]:
score

array([[ 1,  4,  2,  9,  9],
       [ 3,  2,  7,  3, 10]])

In [ ]:
score.T #역행렬(행렬 변경)

array([[ 1,  3],
       [ 4,  2],
       [ 2,  7],
       [ 9,  3],
       [ 9, 10]])

In [ ]:
#공분산 구하기 : ((score - 평균)와 (score의 역행렬 - 평균)의 곱) / (데이터수 - 1)
np.dot(score - 5, score.T - 5) / (5 - 1) 

array([[14.5 ,  4.25],
       [ 4.25, 11.5 ]])

In [ ]:
df = pd.DataFrame({
    "eng_rank":[1, 4, 2, 9, 9], #영어 등수
    "kor_rank":[3, 2, 7, 3, 10] #국어 등수
})

df.cov() #공분산 구하기(검증)

eng_rank  kor_rank
eng_rank     14.50      4.25
kor_rank      4.25     11.50

## 고유값/고유벡터

In [ ]:
eigen_value = np.array(
    [[7, 0],
    [0, 2]]
)

In [ ]:
eigen_vector = np.array(
    [[2, 3],
     [-1, 1]]
)

In [ ]:
np.dot(eigen_value, eigen_vector)

array([[14, 21],
       [-2,  2]])

In [ ]:
np.matmul(eigen_value, eigen_vector)

array([[14, 21],
       [-2,  2]])

# 수학적 풀이 P.187 - 

In [ ]:
data = { 
    "x1" : [0.2, 0.45, 0.33, 0.54, 0.77],
    "x2" : [5.6, 5.87, 6.37, 7.9, 7.87],
    "x3" : [3.56, 2.4, 1.95, 1.32, 0.98],
    "y" : [100, 70, 60, 45, 30]
}

df = pd.DataFrame(data) #데이터프레임으로 변환

In [ ]:
X = df[["x1", "x2", "x3"]] #독립변수

In [ ]:
X.mean() #각 독립변수의 평균 계산

x1    0.458
x2    6.722
x3    2.042
dtype: float64

In [ ]:
X.std() #각 독립변수의 표준편차 계산

x1    0.216264
x2    1.097073
x3    1.011197
dtype: float64

In [ ]:
#Standardization(표준화)
#평균 = 0, 표준편차 = 1로 만들어 줌
#새로운 값 = (원래 값 - 평균) / 표준편차
X = (X-X.mean())/X.std()
X

x1        x2        x3
0 -1.192988 -1.022721  1.501191
1 -0.036992 -0.776612  0.354036
2 -0.591870 -0.320854 -0.090981
3  0.379167  1.073766 -0.714005
4  1.442683  1.046420 -1.050240

In [ ]:
X.mean() #표준화 이후 평균: 거의 0

x1    0.000000e+00
x2    4.440892e-17
x3   -4.440892e-17
dtype: float64

In [ ]:
X.std() #표준화 이후 표준편차: 1

x1    1.0
x2    1.0
x3    1.0
dtype: float64

In [ ]:
#공분산 행렬
#(X.T 곱하기 X)/(전체 데이터의 수 - 1) < 강의자료에 오타 나있어요!@
X_cov = np.dot(X.T, X) / 4
X_cov   

array([[ 1.        ,  0.83887873, -0.88401004],
       [ 0.83887873,  1.        , -0.91168074],
       [-0.88401004, -0.91168074,  1.        ]])

In [ ]:
#공분산 행렬의 고유값, 고유벡터
eigenvalue, eigenvector = np.linalg.eig(X_cov)

print("고유값: ", eigenvalue)
print("고유벡터: ")
print(eigenvector)

고유값:  [2.75671923 0.16413978 0.07914099]
고유벡터: 
[[ 0.56993665  0.7754158   0.27185024]
 [ 0.57618187 -0.61301734  0.54057764]
 [-0.58582135  0.15145983  0.79616158]]


In [ ]:
eigenvector.T #행열 변경

array([[ 0.56993665,  0.57618187, -0.58582135],
       [ 0.7754158 , -0.61301734,  0.15145983],
       [ 0.27185024,  0.54057764,  0.79616158]])

전체에서 77% 이상의 고유값을 갖는 벡터를 사용해 회귀분석을 실행함 

In [ ]:
#고유값이 갖는 비율 계산
eigenvalue / sum(eigenvalue) #고유값 / 전체 고유값의 합

array([0.91890641, 0.05471326, 0.02638033])

In [ ]:
#Z1(첫번째 PC) 계산
z1 = X.dot(eigenvector.T[0])
z1

0   -2.148630
1   -0.675954
2   -0.468900
3    1.253065
4    2.040419
dtype: float64

회귀분석

In [ ]:
from sklearn import  linear_model

In [ ]:
linear_regression = linear_model.LinearRegression()

In [ ]:
#모든 독립변수로 선형회귀 시 R square
linear_regression.fit(X = X, y = df["y"]) #회귀식 적합
linear_regression.score(X = X, y = df["y"]) #R square

0.9978441052442628

In [ ]:
#z1 값을 독립변수로 선형회귀 시 R square
linear_regression.fit(X = pd.DataFrame(z1), y = df["y"]) #회귀식 적합
linear_regression.score(X = pd.DataFrame(z1), y = df["y"]) #R square

0.959290206663969

# PCA를 통한 Feature Selection

> **PCA (Principle Component Analysis)** : 차원의 수를 줄인다 = 분석에 사용될 데이터의 수를 줄임

* 데이터의 차원을 줄이는 방법 > 특정한 축에 정사영
* 정사영 시키다 보면 정보의 유실이 생길 수 있음 > 데이터의 분산이 가장 넓은 지역(축)을 찾음
* '공분산 행렬의 고유벡터 방향'을 축으로 설정
* 이 고유벡터를 통해 만들어지는 축을 'PC(Principle Component)'라고 함! (기존 변수의 선형결합)


In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components = 3) #3개의 PC를 찾을 것임

In [ ]:
pca.fit(X) #PCs 계산

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
print("고유값: ", pca.singular_values_) 
print("고유벡터:\n", pca.components_.T)

고유값:  [3.32067416 0.81028337 0.56264017]
고유벡터:
 [[-0.56993665  0.7754158  -0.27185024]
 [-0.57618187 -0.61301734 -0.54057764]
 [ 0.58582135  0.15145983 -0.79616158]]


In [ ]:
z = pca.fit_transform(X) #X에 고유값 벡터를 곱해서 리턴
z

array([[ 2.14863038, -0.07074582, -0.31801621],
       [ 0.6759543 ,  0.50101454,  0.1480055 ],
       [ 0.46889967, -0.27603645,  0.40678208],
       [-1.25306486, -0.47236838, -0.115067  ],
       [-2.04041949,  0.31813611, -0.12170436]])

In [ ]:
z1 = z.T[0] #고유값이 차지하는 비율이 가장 큰 첫번째 PC 선택
z1

array([ 2.14863038,  0.6759543 ,  0.46889967, -1.25306486, -2.04041949])

In [ ]:
linear_regression.fit(X = pd.DataFrame(z1), y = df["y"])
linear_regression.score(X = pd.DataFrame(z.T[0]), y = df["y"])

0.959290206663969

#보스턴 집값

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.style.use("ggplot")

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
from sklearn.datasets import load_boston
boston_dataset = load_boston() #데이터 로드 

In [ ]:
boston = pd.DataFrame(boston_dataset.data, columns = boston_dataset.feature_names)
boston.head()

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [ ]:
y = boston_dataset.target #종속 변수_집값

데이터 전처리

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() #표준화 객체(평균 = 0, 표준편차 = 1)
scaler.fit(boston)
X = scaler.transform(boston) #표준화

In [ ]:
X = pd.DataFrame(X, columns = boston_dataset.feature_names)

PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 13)
pca.fit(X)

print("고유값: ", pca.singular_values_)
print("고유벡터: \n", pca.components_.T)

고유값:  [55.6793095  26.93022859 25.07516773 20.83105866 20.55278239 18.23864114
 16.45874174 14.15716218 11.83779223 10.55653065  9.70171478  9.25566343
  5.66883461]
고유벡터: 
 [[ 0.2509514  -0.31525237  0.24656649  0.06177071  0.08215692 -0.21965961
   0.77760721  0.15335048  0.26039028  0.01936913 -0.10964435  0.08676107
   0.0459523 ]
 [-0.25631454 -0.3233129   0.29585782  0.12871159  0.32061699 -0.3233881
  -0.27499628 -0.40268031  0.35813749  0.26752723  0.26275629 -0.07142528
  -0.08091897]
 [ 0.34667207  0.11249291 -0.01594592  0.01714571 -0.00781119 -0.0761379
  -0.33957645  0.17393172  0.64441615 -0.36353226 -0.30316943 -0.11319963
  -0.25107654]
 [ 0.00504243  0.45482914  0.28978082  0.81594136  0.08653094  0.16749014
   0.07413621 -0.02466215 -0.01372777 -0.00618184  0.01392667 -0.00398268
   0.03592171]
 [ 0.34285231  0.21911553  0.12096411 -0.12822614  0.13685356 -0.15298267
  -0.19963484  0.08012056 -0.01852201  0.23105645  0.11131888  0.80432257
   0.04363045]
 [-0.18924257

고유값의 비율의 합이 77% 이상이 되도록 데이터 선택

In [ ]:
pca.singular_values_ / sum(pca.singular_values_)

array([0.22731479, 0.1099446 , 0.10237118, 0.0850443 , 0.08390821,
       0.07446057, 0.067194  , 0.05779763, 0.04832864, 0.0430978 ,
       0.03960795, 0.03778691, 0.02314343])

In [ ]:
sum(pca.singular_values_[0:8]) / sum(pca.singular_values_) #8번째 고유값까지의 비율의 합이 77% 이상

0.8080352767158057

고유값 벡터로 만들어지는 Z (PCs)

In [ ]:
z = pca.transform(X)
z

array([[-2.09829747,  0.77311275,  0.34294273, ..., -0.03300036,
         0.01944023,  0.36597533],
       [-1.45725167,  0.59198521, -0.69519931, ..., -0.64080983,
        -0.12579741, -0.07071949],
       [-2.07459756,  0.5996394 ,  0.1671216 , ..., -0.48755672,
         0.13332653, -0.0140218 ],
       ...,
       [-0.31236047,  1.15524644, -0.40859759, ...,  0.11565634,
         0.28196407,  0.06247358],
       [-0.27051907,  1.04136158, -0.58545406, ...,  0.0870124 ,
         0.30170082,  0.05436991],
       [-0.12580322,  0.76197805, -1.294882  , ...,  0.18432101,
         0.23273318,  0.01970872]])

In [ ]:
z.shape #행 506개, 열 13개

(506, 13)

In [ ]:
z = z.T #행열 변환
z.shape

(13, 506)

In [ ]:
z = z[0:8] #8번째 행까지 리턴
z = z.T #행열 변환
z.shape

(506, 8)

In [ ]:
zDF = pd.DataFrame(z) #데이터프레임으로 변환
zDF.head()

0         1         2  ...         5         6         7
0 -2.098297  0.773113  0.342943  ... -0.315338  0.318641  0.295832
1 -1.457252  0.591985 -0.695199  ...  0.264223  0.553861 -0.223670
2 -2.074598  0.599639  0.167122  ...  0.448095  0.484560  0.105166
3 -2.611504 -0.006871 -0.100284  ...  0.664649  0.622641  0.255941
4 -2.458185  0.097712 -0.075348  ...  0.617047  0.705086 -0.134524

[5 rows x 8 columns]

회귀분석

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
linear_regression = LinearRegression()
linear_regression.fit(zDF, y) #회귀식 적합

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
linear_regression.score(X = zDF, y = y)

0.7055977712036576

#참고

선형대수학, 통계학 관련 개념 >  [공돌이의 수학정리노트](https://angeloyeo.github.io/archive.html?tag=%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98) 


선형대수학 고유값, 고유벡터 > [로스카츠](https://losskatsu.github.io/linear-algebra/eigen/#%EA%B3%A0%EC%9C%A0%EA%B0%92-%EA%B3%A0%EC%9C%A0%EB%B2%A1%ED%84%B0%EC%9D%98-%EC%9D%98%EB%AF%B8)

PCA > [네이버 블로그](https://blog.naver.com/PostView.nhn?blogId=sw4r&logNo=221031465518&parentCategoryNo=&categoryNo=43&viewDate=&isShowPopularPosts=true&from=search)